### ISSUE TITLE
"An error has occurred"

### ISSUE THREAD

**Issue by CWWhitney** [CWWhitney/Decision_Analysis_Course#28]
Getting a strange error on the web app again "An error has occurred"

<img width="729" alt="Screenshot 2024-04-01 at 1 24 06 PM" src="https://github.com/CWWhitney/Decision_Analysis_Course/assets/19190662/2f534cd3-cb73-479c-9c4c-f360795397c0">

The error point in the logs: 

04/01 11:21:49.314 (GMT)
Error in value[[3L]](cond) : parse error: trailing garbage
04/01 11:21:49.314 (GMT)
":{},"value":["0.10.1"]}]}]} {"type":"list","attributes":{},
04/01 11:21:49.314 (GMT)
(right here) ------^
04/01 11:21:49.314 (GMT)
Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
04/01 11:21:49.314 (GMT)
Shiny R Markdown document exiting ...
04/01 11:21:49.314 (GMT)
Execution halted

The full logs: 

[rstudio-connect.234.0.1222.run_app.g6WZmicSktyEeDdt.log](https://github.com/CWWhitney/Decision_Analysis_Course/files/14822903/rstudio-connect.234.0.1222.run_app.g6WZmicSktyEeDdt.log)

**Comment by CWWhitney** [comment]
Related to https://github.com/rstudio/learnr/issues/597

**Comment by CWWhitney** [comment]
@PrajnaKARai is going to rebuild and open a pull request - hopefully this will fix the issue

**Comment by PrajnaKARai** [comment]
@CWWhitney, I have already edited what we spoke about earlier today and pushed it under the branch name '2024.' Can you please check if the issue persists?
