### ISSUE TITLE
Error: Error: Internal Server Error [500]

### ISSUE THREAD

**Issue by CWWhitney** [CWWhitney/Decision_Analysis_Course#6]
Unable to chase this error - Everything on the Rstudio Connect server ran well and the page said 'Activation Complete' but the website just has 'Error: Error: Internal Server Error [500]'. No notes from the build configuration. 
![Screenshot 2023-04-27 at 5 13 04 PM](https://user-images.githubusercontent.com/19190662/234907254-c21d21f7-98af-46d8-894f-c3aa8176b0bd.png)

**Comment by CWWhitney** [comment]
Updated devtools with devtools::install_github("rstudio/rsconnect")
Reactivated the site with the RStudio Connect server.
Followed the steps (that I could) in Troubleshooting https://support.posit.co/hc/en-us/articles/360001230774-Troubleshooting-Deployments-

**Comment by mthomas-ketchbrook** [comment]
Hey, @CWWhitney -- when you say:

> "Everything on the Rstudio Connect server ran well and the page said 'Activation Complete'"

what were you working on / running?  Were you renewing the Connect license and updating the activation code?

**Comment by CWWhitney** [comment]
Hi @mthomas-ketchbrook 
No, I did not do any of that. I was just using Info>Update Now in the Rstudio Connect to build from the git repository. The 500 error started appearing sometime today before all that.  Should I be renewing the Connect license and updating the activation code?

**Comment by mthomas-ketchbrook** [comment]
Are you seeing the 500 error when you open the Calibration App, or after entering your username/password to authenticate into the RStudio Connect platform?

**Comment by CWWhitney** [comment]
Same issue with the calibration app https://agtools.app/calibration_app/
I have entered my username and password to sign in to the RStudio Connect platform. Not sure about using them to authenticate.

**Comment by johanneskopton** [comment]
Hmm.. do you know when the last time was, where you could confirm that the error was not there?

**Comment by CWWhitney** [comment]
Somehow apparently restarting the server solved the issue
